export const EDIT_POKEMON_CONTENT = {
  TITLE: 'עדכון פוקימון',
  NICKNAME_LABEL: 'כינוי:',
  NICKNAME_PLACEHOLDER: 'הכנס כינוי לפוקימון...',
  FAVORITE_ACTIVE: 'מועדף',
  FAVORITE_INACTIVE: 'לא מועדף',
  SAVE_BUTTON: 'שמור',
  CANCEL_BUTTON: 'ביטול',
  CHARACTER_COUNT_SUFFIX: 'תווים',
  EMOJIS: {
    CLOSE: '✕',
    FAVORITE_ACTIVE: '❤️',
    FAVORITE_INACTIVE: '🤍',
  },
  VALIDATION: {
    MAX_CHARACTERS: 20,
    NEAR_LIMIT_THRESHOLD: 0.8,
  },
} as const;

export const EDIT_POKEMON_CONFIG = {
  validation: {
    maxCharacters: EDIT_POKEMON_CONTENT.VALIDATION.MAX_CHARACTERS,
    nearLimitThreshold: EDIT_POKEMON_CONTENT.VALIDATION.NEAR_LIMIT_THRESHOLD,
  },

  text: {
    title: EDIT_POKEMON_CONTENT.TITLE,
    nicknameLabel: EDIT_POKEMON_CONTENT.NICKNAME_LABEL,
    nicknamePlaceholder: EDIT_POKEMON_CONTENT.NICKNAME_PLACEHOLDER,
    characterCountSuffix: EDIT_POKEMON_CONTENT.CHARACTER_COUNT_SUFFIX,
    favoriteActive: EDIT_POKEMON_CONTENT.FAVORITE_ACTIVE,
    favoriteInactive: EDIT_POKEMON_CONTENT.FAVORITE_INACTIVE,
    saveButton: EDIT_POKEMON_CONTENT.SAVE_BUTTON,
    cancelButton: EDIT_POKEMON_CONTENT.CANCEL_BUTTON,
  },

  emojis: {
    close: EDIT_POKEMON_CONTENT.EMOJIS.CLOSE,
    favoriteActive: EDIT_POKEMON_CONTENT.EMOJIS.FAVORITE_ACTIVE,
    favoriteInactive: EDIT_POKEMON_CONTENT.EMOJIS.FAVORITE_INACTIVE,
  },
} as const;
